name: frontend
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.12.0
  flutter_riverpod: ^2.5.1
  geolocator: ^12.0.0
  image_picker: ^1.1.2
  http: ^1.2.1
  flutter_compass: ^0.7.0
  pointer_interceptor: ^0.10.1
  shared_preferences: ^2.2.3
  url_launcher: ^6.3.2
  firebase_core: ^4.12.1
  firebase_messaging: ^16.4.3
  geocoding: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/